"""genre

Revision ID: 1953446aa75f
Revises: 1d198f467008
Create Date: 2024-08-01 13:14:28.626092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1953446aa75f'
down_revision = '1d198f467008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_stats', schema=None) as batch_op:
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
